# Generated by Django 4.2.3 on 2023-07-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('package_id', models.IntegerField(max_length=50, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('version', models.CharField(max_length=50)),
                ('node_id', models.IntegerField(max_length=50)),
            ],
        ),
    ]
