# Generated by Django 4.2.3 on 2023-07-20 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npcil_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='node_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='package',
            name='package_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
